FROM node:24-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/gateway/package.json apps/gateway/package.json
COPY shared/package.json shared/package.json

RUN pnpm install --frozen-lockfile --filter gateway... --filter @my-apps/shared...

COPY apps/gateway ./apps/gateway
COPY shared ./shared
RUN pnpm --filter @my-apps/shared... build
RUN pnpm --filter gateway... build

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/gateway/node_modules ./apps/gateway/node_modules
COPY --from=builder /app/apps/gateway/dist ./apps/gateway/dist
COPY --from=builder /app/apps/gateway/package.json ./apps/gateway/package.json
COPY --from=builder /app/shared ./shared

WORKDIR /app/apps/gateway
EXPOSE 4050

CMD ["node", "dist/main.js"]